### ISSUE TITLE
Addition of index should not be required

### ISSUE THREAD

**Issue by pbchase** [ctsit/auto_populate_fields#28]
The addition of an index at https://github.com/ctsit/auto_populate_fields/blob/46df577507601e7a5fbcd6bc7bd86e06fddcec76/ExternalModule.php#L46 should not be required.  See http://www.mysqltutorial.org/mysql-index/mysql-composite-index/ and the existing DDL of the `redcap_log_event` table. The structure of the composite indices in `redcap_log_event` should allow performant queries on just `project_id`

Verify this is true on a large `redcap_log_event` table and remove all traces of this index-add operation.

**Comment by ChemiKyle** [comment]
I'm not seeing any significant difference in page loads with `project_id` set as an index vs without in small test projects, and does not seem to scale with (mostly unrelated) extra rows in `redcap_log_event` (see table below for metrics). Since it's acting as index due to the `user_project` I don't expect it will change at all, but I'd like to test with a form that has a long history and a large number of fields using `@DEFAULT-FROM-PREVIOUS-EVENT` to be sure.

Metric|Value
:---|---:
Data|1.9GB
Index|288MB
Total Rows|>1.5 million
Rows with same project_id|528
Rows with same project_id and pk|17

**Comment by pbchase** [comment]
addressed by PR #29

**Comment by ChemiKyle** [comment]
To clarify, PR #29 does not _retroactively remove_ the index status of `project_id` in `redcap_log_event` on servers where it has been activated. One must still 
```mysql
ALTER TABLE `redcap_log_event` DROP INDEX `project_id`;
```

**Comment by pbchase** [comment]
@ChemiKyle, yes, I am aware of the omission of the deletion. I think that is the better choice to make.
